default: cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java
	javac cpsc2150/connectX/Connect4Game.java
	javac	cpsc2150/connectX/GameBoard.java

run: cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java
	java cpsc2150.connectX/Connect4Game

clean:
	rm -f cpsc2150/connectX/*.class
