default:
	javac cpsc2150/connectX/Connect4Game.java
	javac	cpsc2150/connectX/GameBoard.java
	javac	cpsc2150/connectX/IGameBoard.java

run:
	java cpsc2150.connectX/Connect4Game

clean:
	rm -f cpsc2150/connectX/*.class
